# -*- coding: utf-8 -*-
"""Assessment tool-1 module 2&3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n6IQWABC_AaHBJ7dXTNY9vvlqxHN_XvC
"""

import tensorflow as tf
import numpy as np

# Input numbers
x = np.array([0,1,2,3,4,5,6,7,8,9], dtype=float)

# Labels (0 = Even, 1 = Odd)
y = np.array([0,1,0,1,0,1,0,1,0,1], dtype=float)

# Define the input layer explicitly
inputs = tf.keras.Input(shape=(1,))

model = tf.keras.Sequential([
    inputs,
    tf.keras.layers.Dense(8, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(x, y, epochs=300, verbose=0)

print("Prediction for 12:", model.predict(np.array([12]), verbose=0))
print("Prediction for 15:", model.predict(np.array([15]), verbose=0))

import sys
!{sys.executable} -m pip install pydot graphviz

from tensorflow.keras.utils import plot_model

# Visualize the model architecture
plot_model(model, show_shapes=True, show_layer_names=True)

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# -----------------------------
# Create Synthetic Disease Data
# -----------------------------
np.random.seed(42)

n = 1000

age = np.random.randint(20, 80, n)
bp = np.random.randint(90, 180, n)
sugar = np.random.randint(70, 220, n)
cholesterol = np.random.randint(120, 320, n)

# Disease rule
disease = ((bp > 140) & (sugar > 140) | (cholesterol > 240)).astype(int)

data = pd.DataFrame({
    'Age': age,
    'BloodPressure': bp,
    'Sugar': sugar,
    'Cholesterol': cholesterol,
    'Disease': disease
})

print(data.head())

# -----------------------------
# Prepare Data
# -----------------------------
X = data[['Age','BloodPressure','Sugar','Cholesterol']]
y = data['Disease']

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# -----------------------------
# Build Neural Network
# -----------------------------
model = Sequential([
    Dense(16, activation='relu', input_shape=(4,)),
    Dense(8, activation='relu'),
    Dense(1, activation='sigmoid')
])

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

# -----------------------------
# Train Model
# -----------------------------
history = model.fit(
    X_train,
    y_train,
    epochs=30,
    batch_size=32,
    validation_split=0.2,
    verbose=1
)

# -----------------------------
# Evaluate
# -----------------------------
loss, accuracy = model.evaluate(X_test, y_test)

print("\nTest Accuracy:", accuracy)

# -----------------------------
# Predict One Patient
# -----------------------------
sample = np.array([[50,160,180,260]])
sample = scaler.transform(sample)

prediction = model.predict(sample)

if prediction[0][0] > 0.5:
    print("Disease Detected")
else:
    print("Healthy")

# -----------------------------
# Plot Accuracy
# -----------------------------
plt.figure(figsize=(8,5))
plt.plot(history.history['accuracy'], label='Training Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.title("Model Accuracy")
plt.legend()
plt.grid(True)
plt.show()

# -----------------------------
# Plot Loss
# -----------------------------
plt.figure(figsize=(8,5))
plt.plot(history.history['loss'], label='Training Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Model Loss")
plt.legend()
plt.grid(True)
plt.show()